In [43]:
import pandas as pd
original_data = pd.read_csv('../Original data/earthquake_data.csv')

Original data is presented below.

In [44]:
original_data.head()

,"In general, how worried are you about earthquakes?","How worried are you about the Big One, a massive, catastrophic earthquake?","Do you think the ""Big One"" will occur in your lifetime?",Have you ever experienced an earthquake?,"Have you or anyone in your household taken any precautions for an earthquake (packed an earthquake survival kit, prepared an evacuation plan, etc.)?",How familiar are you with the San Andreas Fault line?,How familiar are you with the Yellowstone Supervolcano?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,Not at all worried,Not so worried,No,"Yes, one or more minor ones",No,Somewhat familiar,Not so familiar,18 - 29,Male,Prefer not to answer,New England
1,Somewhat worried,Very worried,No,"Yes, one or more minor ones",No,Not at all familiar,Not at all familiar,18 - 29,Male,"$75,000 to $99,999",East North Central
2,Not so worried,Somewhat worried,No,"Yes, one or more minor ones",No,Very familiar,Somewhat familiar,18 - 29,Male,"$10,000 to $24,999",Pacific
3,Not so worried,Not so worried,No,"Yes, one or more minor ones",No,Very familiar,Not so familiar,18 - 29,Male,"$25,000 to $49,999",West South Central
4,Not so worried,Not so worried,Yes,"Yes, one or more minor ones",No,Somewhat familiar,Extremely familiar,18 - 29,Male,"$200,000 and up",Middle Atlantic

Original names of the columns have been shortened as follows:

In [54]:
new_names = {
    original_data.columns[0]: 'Worried about earthquakes',
    original_data.columns[1]: 'Worried about the Big One',
    original_data.columns[2]: 'Will the Big One occur in your life?',
    original_data.columns[3]: 'Experienced an earthquake?',
    original_data.columns[4]: 'Taken precautions?',
    original_data.columns[5]: 'Familiar with SA Fault line?',
    original_data.columns[6]: 'Familiar with the Yellowstone Supervolcano?',
    original_data.columns[8]: 'Gender',
    original_data.columns[9]: 'Household income'}


new_data = original_data.rename(columns=new_names)
new_data.dropna(subset = ['Age', 'Gender'], inplace=True)
display(new_data)
print(f'The number of deleted records with NaN values: {original_data.shape[0] - new_data.shape[0]}')

,Worried about earthquakes,Worried about the Big One,Will the Big One occur?,Experienced an earthquake?,Taken precautions?,Familiar with SA Fault line?,Familiar with the Yellowstone Supervolcano?,Age,Gender,Household income,US Region
0,Not at all worried,Not so worried,No,"Yes, one or more minor ones",No,Somewhat familiar,Not so familiar,18 - 29,Male,Prefer not to answer,New England
1,Somewhat worried,Very worried,No,"Yes, one or more minor ones",No,Not at all familiar,Not at all familiar,18 - 29,Male,"$75,000 to $99,999",East North Central
2,Not so worried,Somewhat worried,No,"Yes, one or more minor ones",No,Very familiar,Somewhat familiar,18 - 29,Male,"$10,000 to $24,999",Pacific
3,Not so worried,Not so worried,No,"Yes, one or more minor ones",No,Very familiar,Not so familiar,18 - 29,Male,"$25,000 to $49,999",West South Central
4,Not so worried,Not so worried,Yes,"Yes, one or more minor ones",No,Somewhat familiar,Extremely familiar,18 - 29,Male,"$200,000 and up",Middle Atlantic
...,...,...,...,...,...,...,...,...,...,...,...
1007,Not at all worried,Not at all worried,No,No,No,Somewhat familiar,Somewhat familiar,60,Female,Prefer not to answer,New England
1008,Not at all worried,Not at all worried,No,"Yes, one or more minor ones",No,Very familiar,Not so familiar,60,Male,Prefer not to answer,Pacific
1009,Not so worried,Somewhat worried,No,"Yes, one or more major ones",Yes,Extremely familiar,Somewhat familiar,60,Female,"$50,000 to $74,999",Pacific
1010,Not so worried,Extremely worried,No,"Yes, one or more minor ones",No,Somewhat familiar,Somewhat familiar,30 - 44,Female,Prefer not to answer,Middle Atlantic
1011,Not at all worried,Not so worried,No,No,No,Somewhat familiar,Somewhat familiar,30 - 44,Female,"$50,000 to $74,999",East North Central

The number of deleted records with NaN values: 12

In the next table only 3 columns will be displayed: age, gender and the answer to the question whether the Big One will occur in the person's lifetime.

In [56]:
small_data = new_data[[new_data.columns[7], new_data.columns[8], new_data.columns[2]]]
display(small_data)

          Age  Gender Will the Big One occur?
0     18 - 29    Male                      No
1     18 - 29    Male                      No
2     18 - 29    Male                      No
3     18 - 29    Male                      No
4     18 - 29    Male                     Yes
...       ...     ...                     ...
1007       60  Female                      No
1008       60    Male                      No
1009       60  Female                      No
1010  30 - 44  Female                      No
1011  30 - 44  Female                      No

[1001 rows x 3 columns]

In [57]:
new_data.to_csv('../Analysis data/new_data.csv')
small_data.to_csv('../Analysis data/small_data.csv')